import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { createInterface } from "node:readline/promises";

const ROOT = process.cwd();
const CONFIG_PATH = path.join(ROOT, "proti.config.json");
const WEB_ENV_PATH = path.join(ROOT, "web", ".env.local");
const STUDIO_ENV_PATH = path.join(ROOT, "studio", ".env.local");

function slugify(value) {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function normalizeLocale(value) {
  return value.trim().toLowerCase();
}

function normalizeDomain(value) {
  return value
    .trim()
    .toLowerCase()
    .replace(/^https?:\/\//, "")
    .replace(/\/.*$/, "")
    .replace(/\.$/, "");
}

function splitCsv(value) {
  return value
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

function parseLocales(value) {
  const seen = new Set();

  return splitCsv(value).map((entry) => {
    const separator = entry.indexOf(":");
    const rawCode = separator >= 0 ? entry.slice(0, separator) : entry;
    const rawLabel = separator >= 0 ? entry.slice(separator + 1) : entry;
    const code = normalizeLocale(rawCode);
    const label = rawLabel.trim() || code;

    if (!/^[a-z]{2,3}-[a-z]{2}$/.test(code)) {
      throw new Error(
        `Invalid locale "${code}". Proti uses language-region format, e.g. en-us or fr-ca.`,
      );
    }

    if (seen.has(code)) {
      throw new Error(`Duplicate locale "${code}".`);
    }

    seen.add(code);
    return { code, label };
  });
}

async function fileExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function readJson(filePath, fallback = null) {
  if (!(await fileExists(filePath))) return fallback;
  return JSON.parse(await fs.readFile(filePath, "utf8"));
}

function parseEnv(source) {
  const values = {};

  for (const rawLine of source.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;

    const index = line.indexOf("=");
    if (index < 0) continue;

    const key = line.slice(0, index).trim();
    let value = line.slice(index + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    values[key] = value;
  }

  return values;
}

async function readEnv(filePath) {
  if (!(await fileExists(filePath))) return {};
  return parseEnv(await fs.readFile(filePath, "utf8"));
}

function envValue(value) {
  const stringValue = String(value ?? "");
  return /[\s#"'`]/.test(stringValue)
    ? JSON.stringify(stringValue)
    : stringValue;
}

async function writeEnv(filePath, values, heading) {
  const content = [
    `# ${heading}`,
    "# Generated by pnpm proti:init",
    "",
    ...Object.entries(values).map(
      ([key, value]) => `${key}=${envValue(value)}`,
    ),
    "",
  ].join("\n");

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content);
}

async function prompt(rl, scriptedAnswers, state, label, fallback = "") {
  const suffix = fallback ? ` [${fallback}]` : "";

  if (scriptedAnswers) {
    const answer = (scriptedAnswers[state.index++] ?? "").trim();
    console.log(`${label}${suffix}: ${answer}`);
    return answer || fallback;
  }

  const answer = (await rl.question(`${label}${suffix}: `)).trim();
  return answer || fallback;
}

async function readScriptedAnswers() {
  if (process.stdin.isTTY) return null;

  let input = "";
  for await (const chunk of process.stdin) input += chunk;
  return input.split(/\r?\n/);
}

async function updatePackageName(filePath, name) {
  if (!(await fileExists(filePath))) return;
  const pkg = JSON.parse(await fs.readFile(filePath, "utf8"));
  pkg.name = name;
  await fs.writeFile(filePath, `${JSON.stringify(pkg, null, 2)}\n`);
}

const existingConfig = (await readJson(CONFIG_PATH, {})) ?? {};
const existingWebEnv = await readEnv(WEB_ENV_PATH);
const existingStudioEnv = await readEnv(STUDIO_ENV_PATH);
const scriptedAnswers = await readScriptedAnswers();
const scriptedState = { index: 0 };
const rl = scriptedAnswers
  ? null
  : createInterface({ input: process.stdin, output: process.stdout });

try {
  console.log("\nProti project initialization\n");

  const projectName = await prompt(
    rl,
    scriptedAnswers,
    scriptedState,
    "Project name",
    existingConfig.projectName || "Proti Site",
  );
  const packageName = slugify(
    await prompt(
      rl,
      scriptedAnswers,
      scriptedState,
      "Package/project slug",
      existingConfig.packageName || slugify(projectName) || "proti-site",
    ),
  );
  const projectId = await prompt(
    rl,
    scriptedAnswers,
    scriptedState,
    "Sanity project ID",
    existingConfig.sanity?.projectId ||
      existingWebEnv.NEXT_SANITY_PROJECT_ID ||
      existingStudioEnv.SANITY_STUDIO_PROJECT_ID ||
      "",
  );

  if (!/^[a-z0-9-]+$/i.test(projectId)) {
    throw new Error("A valid Sanity project ID is required.");
  }

  const dataset = await prompt(
    rl,
    scriptedAnswers,
    scriptedState,
    "Sanity dataset",
    existingConfig.sanity?.dataset ||
      existingWebEnv.NEXT_SANITY_DATASET ||
      existingStudioEnv.SANITY_STUDIO_DATASET ||
      "production",
  );
  const studioUrl = await prompt(
    rl,
    scriptedAnswers,
    scriptedState,
    "Studio URL used by the Web app",
    existingConfig.sanity?.studioUrl ||
      existingWebEnv.NEXT_SANITY_STUDIO_URL ||
      "http://localhost:3333",
  );
  const previewUrl = await prompt(
    rl,
    scriptedAnswers,
    scriptedState,
    "Web URL used by Sanity Presentation",
    existingConfig.sanity?.previewUrl ||
      existingStudioEnv.SANITY_STUDIO_PREVIEW_URL ||
      "http://localhost:3000",
  );
  const siteName = await prompt(
    rl,
    scriptedAnswers,
    scriptedState,
    "Initial Site name",
    existingConfig.site?.name || projectName,
  );
  const siteKey = slugify(
    await prompt(
      rl,
      scriptedAnswers,
      scriptedState,
      "Initial Site key",
      existingConfig.site?.key || packageName,
    ),
  );
  const domains = Array.from(
    new Set(
      splitCsv(
        await prompt(
          rl,
          scriptedAnswers,
          scriptedState,
          "Site domains (comma separated)",
          existingConfig.site?.domains?.join(", ") || "localhost",
        ),
      )
        .map(normalizeDomain)
        .filter(Boolean),
    ),
  );

  if (domains.length === 0)
    throw new Error("At least one Site domain is required.");

  const defaultLocale = normalizeLocale(
    await prompt(
      rl,
      scriptedAnswers,
      scriptedState,
      "Default locale",
      existingConfig.site?.defaultLocale || "en-us",
    ),
  );

  if (!/^[a-z]{2,3}-[a-z]{2}$/.test(defaultLocale)) {
    throw new Error(
      `Invalid default locale "${defaultLocale}". Use language-region format, e.g. en-us.`,
    );
  }

  const existingLocales =
    existingConfig.site?.locales
      ?.map(({ code, label }) => `${code}:${label}`)
      .join(", ") || "en-us:English (US), es-us:Spanish (US)";
  const locales = parseLocales(
    await prompt(
      rl,
      scriptedAnswers,
      scriptedState,
      "Supported locales as code:label (comma separated)",
      existingLocales,
    ),
  );

  if (!locales.some(({ code }) => code === defaultLocale)) {
    throw new Error(
      `Default locale "${defaultLocale}" must be included in Supported locales.`,
    );
  }

  const config = {
    version: 1,
    projectName,
    packageName,
    sanity: { projectId, dataset, studioUrl, previewUrl },
    site: { name: siteName, key: siteKey, domains, defaultLocale, locales },
  };

  await fs.writeFile(CONFIG_PATH, `${JSON.stringify(config, null, 2)}\n`);
  await writeEnv(
    WEB_ENV_PATH,
    {
      NEXT_SANITY_PROJECT_ID: projectId,
      NEXT_SANITY_DATASET: dataset,
      NEXT_SANITY_STUDIO_URL: studioUrl,
      SANITY_API_READ_TOKEN: existingWebEnv.SANITY_API_READ_TOKEN || "",
      SANITY_API_WRITE_TOKEN: existingWebEnv.SANITY_API_WRITE_TOKEN || "",
      SANITY_REVALIDATE_SECRET: existingWebEnv.SANITY_REVALIDATE_SECRET || "",
    },
    "Proti Web local environment",
  );
  await writeEnv(
    STUDIO_ENV_PATH,
    {
      SANITY_STUDIO_PROJECT_ID: projectId,
      SANITY_STUDIO_DATASET: dataset,
      SANITY_STUDIO_TITLE: projectName,
      SANITY_STUDIO_PREVIEW_URL: previewUrl,
    },
    "Proti Studio local environment",
  );

  await updatePackageName(path.join(ROOT, "package.json"), packageName);
  await updatePackageName(
    path.join(ROOT, "web", "package.json"),
    `${packageName}-web`,
  );
  await updatePackageName(
    path.join(ROOT, "studio", "package.json"),
    `${packageName}-studio`,
  );

  console.log("\n✓ Wrote proti.config.json");
  console.log("✓ Wrote web/.env.local");
  console.log("✓ Wrote studio/.env.local");
  console.log("✓ Updated package names where package.json files exist");
  console.log("\nNext:");
  console.log("  1. Add any required Sanity tokens to web/.env.local.");
  console.log("  2. Run: pnpm proti:seed");
  console.log("  3. Run: pnpm dev:studio");
  console.log("  4. Run: pnpm dev:web\n");
} finally {
  rl?.close();
}
